### ISSUE TITLE
Has anyone fixed the life pattern ?

### ISSUE THREAD

**Issue by tablatronix** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#261]
Was just curious, cause it is clearly wrong. Maybe bad neighbor code, bad random entropy?

It always winds up with these repeating lines and lots of symmetry

![Screen Shot 2022-03-06 at 8 45 20 AM](https://user-images.githubusercontent.com/807787/156928227-fdce9075-83c9-4f93-a0ac-3398356c9cfc.png)

**Comment by mrfaptastic** [comment]
Not sure what's going on with these aurora examples, the code isn't maintained and may need to be refactored.

**Comment by tablatronix** [comment]
Ill work on them , did these come from fastled? I noticed alot have been modded time use effects.h

I have some working and some working better

**Comment by mrfaptastic** [comment]
The code was originally coped from here: https://github.com/pixelmatix/aurora
