### ISSUE TITLE
How can i write text at the panel 

### ISSUE THREAD

**Issue by hasanedrees25** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#334]
can you let me now how to write text into the panel

**Comment by DarrylStrong** [comment]
Use the Adafruit GFX library...
[https://github.com/adafruit/Adafruit-GFX-Library](url)

**Comment by hasanedrees25** [comment]
@DarrylStrong  could you please post an example .....

**Comment by DarrylStrong** [comment]
https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/blob/master/examples/1_SimpleTestShapes/1_SimpleTestShapes.ino
