### ISSUE TITLE
Display dislocation problem

### ISSUE THREAD

**Issue by 1359450511** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#342]
Hello, I encountered a problem when using your library, as shown in the picture, trying to modify mxconfig.clkphase=false;
mxconfig.latch_ blanking=4; It's no use getting better. Please tell me what the problem is and how to solve it. The 128 * 64 driver chips ICND2013 and ICN2037BP are formed by connecting the 64 * 64 LED board of the platform ESP32 The picture shows a rectangular box and a circle. The rectangular box displays normally but the circle displays abnormally.
![48761AD978ED448C60D6239EC607DEFB](https://user-images.githubusercontent.com/44389709/201929969-f4508196-cbfb-499b-a132-980b550ecf27.jpg)

**Comment by mrfaptastic** [comment]
Did you ever find a solution to this issue?
