### ISSUE TITLE
Clock speed 

### ISSUE THREAD

**Issue by techwide** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#377]
Hi,
I am having some weird problem with LED panels using the latest version, 3.0.3. All works fine with 2.0.7.
Some display shows garbage and some display shows some dots with different colors.

![dotcolor](https://user-images.githubusercontent.com/3874500/213902481-f1aa38b0-dc37-43a0-ab45-a5f452a24e01.jpg)

I have tested many different ways and finally I've found that the clock speeds at CLK pin are different. The clock speed of 3.0.3 version is 33MHz but 2.0.7 version is 10MHz. I assume 10MHz is the correct one.

![scope](https://user-images.githubusercontent.com/3874500/213902361-716f0d64-f295-4288-84b5-9a9e87e435da.jpg)

I've even inserted the following code but the clock is 33MHz.

mxconfig.i2sspeed = HUB75_I2S_CFG::HZ_10M; 

I am not sure whether the clock is adjustable but the clock speed seems to be the problem I am having.

Regards,

Peter

**Comment by mrfaptastic** [comment]
Clock speed is adjustable so should be 10mhz.

What esp32 variant are you using?

**Comment by mrfaptastic** [comment]
Clock speed is adjustable so should be 10mhz.

What esp32 variant are you using?

**Comment by mrfaptastic** [comment]
Can you try the latest git version of the library, and check these values versus what you see in the scope?

```
mxconfig.i2sspeed = HUB75_I2S_CFG::HZ_10M;


mxconfig.i2sspeed = HUB75_I2S_CFG::HZ_20M;
```

**Comment by techwide** [comment]
Yes the clock now works with HZ_10M and HZ_20M.

BTW..PlatformIO does not detect the latest version. It detects only v3.0.2.

**Comment by mrfaptastic** [comment]
Just to be sure HZ_10M gives a 10Mhz clock right?

**Comment by mrfaptastic** [comment]
Thanks again for making this library better.

**Comment by techwide** [comment]
Yes HZ_10M gives a 10Mhz clock and HZ_20M gives a 20Mhz clock as expected!

**Comment by mrfaptastic** [comment]
Thanks again for making this library better.
