### ISSUE TITLE
I2S-ADC acquisition conflict with Panel Library

### ISSUE THREAD

**Issue by i4cy** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#391]
Greetings all,

Not sure what has happened, but recently I2S-ADC acquisition no longer works with the panel library. Everything was working fine with v2.0.7, but now whatever panel library version I use current v3.0.5 or older, I cannot get both the panel and the I2S -ADC to function together. They work mutually exclusively, but not together. I have trimmed down my code to the bare essentials to illustrate the problem.

platformio.ini
```
[env:esp32dev]
platform = espressif32@6.0.0
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
lib_deps = 
	mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.5
	adafruit/Adafruit GFX Library@^1.10.13
	fastled/FastLED@^3.5.0
```

main.cpp
```
#include <Arduino.h>
#include <ESP32-HUB75-MatrixPanel-I2S-DMA.h>

MatrixPanel_I2S_DMA* panel = nullptr;

void hub75_setup(void)
{
    HUB75_I2S_CFG mxconfig;
    mxconfig.mx_height = 32;
    mxconfig.chain_length = 1;

    panel = new MatrixPanel_I2S_DMA(mxconfig);
    panel->begin();
}

void hub75_loop(void)
{
    static uint8_t x, y;

    panel->fillScreen(0);  
    panel->writePixel(x % 64, y % 32, 0xFFFF);
    if (x++ == 64) { x = 0; y++; }
    delay(20);
}

void adc_i2s_setup(void)
{
    const i2s_config_t i2s_config =
    { 
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX | I2S_MODE_ADC_BUILT_IN),
        .sample_rate = 44100,                        
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_ONLY_LEFT,
        .communication_format = I2S_COMM_FORMAT_STAND_I2S,
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
        .dma_buf_count = 2,
        .dma_buf_len = 1024,
        .use_apll = false,
        .tx_desc_auto_clear = false,
        .fixed_mclk = 0
    };

    ESP_ERROR_CHECK( i2s_driver_install(I2S_NUM_0, &i2s_config,  0, NULL) );
    ESP_ERROR_CHECK( i2s_set_adc_mode(ADC_UNIT_1, ADC1_CHANNEL_0) );
}

void adc_i2s_loop(void)
{
    const uint16_t NUM_SAMPLES = 2048;
    static int16_t rawData[NUM_SAMPLES];

    size_t bytesRead = 0;
    ESP_ERROR_CHECK( i2s_adc_enable(I2S_NUM_0) );
    ESP_ERROR_CHECK( i2s_read(I2S_NUM_0, (void*)rawData, NUM_SAMPLES * sizeof(uint16_t), &bytesRead, portMAX_DELAY) );
    ESP_ERROR_CHECK( i2s_adc_disable(I2S_NUM_0) );

    for (uint16_t sample = 0; sample < NUM_SAMPLES; sample++)
    {
        Serial.printf("%04d, %04d\n", sample, rawData[sample]);
    }
}

void setup()
{
    Serial.begin(115200);

    adc_i2s_setup();
    //hub75_setup();    // i2s_adc acquisition stops working when this is uncommented.
}

void loop()
{
    adc_i2s_loop();
    //hub75_loop();    // i2s_adc acquisition stops working when this is uncommented.
}

```

Does anyone have any ideas as to what I maybe doing wrong?
Thanks in advance!

Great library by the way!

**Comment by mrfaptastic** [comment]
If you're using an ESP32, then you'll need to edit this line: https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/blob/da22bb835b0544fec35c06f197e4ae431fdc7605/src/platforms/esp32/esp32_i2s_parallel_dma.hpp#L52

Change it to I2S_NUM_1

**Comment by mrfaptastic** [comment]
You'll need to edit this line: https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/blob/da22bb835b0544fec35c06f197e4ae431fdc7605/src/platforms/esp32/esp32_i2s_parallel_dma.hpp#L52

Change it to I2S_NUM_1

*Or* use the latest git version (just made a change) and set a global compile time definition, like:

```
-DESP32_I2S_DEVICE=I2S_NUM_1
```

**Comment by i4cy** [comment]
Thanks, yes that fixed it.

As I say it was working fine before, so I must have originally changed the ESP32_I2S_DEVICE definition to I2S_NUM_1 and forgotten about it. Subsequently it got overwritten with a file update containing the default definition. I have added the compiler definition as you have suggested so this problem should not reoccur during updates. Thanks also for making this change in the source code.

> Alternatively, I'm not sure if you can use I2S_NUM_1 for your ADC measurements?

Unfortunately not, ADC and DAC I2S streaming can only the I2S_NUM_0 port number.

**Comment by mrfaptastic** [comment]
> I must have originally changed the ESP32_I2S_DEVICE definition to I2S_NUM_1

Don't question your sanity. As part of the 3.x release I changed IS2_NUM to IS2_NUM_0 across all ESP32 boards as the other ESP32's only have one I2S peripheral.
