### ISSUE TITLE
Bug/Mistake in flip_dma_output_buffer() (esp32)?

### ISSUE THREAD

**Issue by Lukaswnd** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#407]
Hi there,
I have an Project with 3 64x32 1/16 panels. I had it running with [SmartMatrix](https://github.com/pixelmatix/SmartMatrix). I decided to switch to this library, since both can use Adafruit_GFX it was very easy to exchange. But even though I ported every setting as close as possible and tried around a bit the Image was not clear and the scrolling Text was lagging. Afer I found out, that it very often skips to display one of the Buffers (using Doublebuffer) the bug was easy to find.

In Tag 3.0.5:
[src/platforms/esp32/esp32_i2s_parallel_dma.cpp:614](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/blob/3.0.5/src/platforms/esp32/esp32_i2s_parallel_dma.cpp#L633)
```
void Bus_Parallel16::flip_dma_output_buffer(int &current_back_buffer_id){

    if ( current_back_buffer_id == 1) {     

        _dmadesc_a[_dmadesc_last].qe.stqe_next = &_dmadesc_b[0]; 

        // Wait until we're now stuck in a _dmadesc_a loop;
        active_dma_buffer_output_count = 0;  
        while (!active_dma_buffer_output_count) {}      
                                        
        _dmadesc_a[_dmadesc_last].qe.stqe_next = &_dmadesc_a[0];  //append the old to the end of the old?
      
      } else {
        _dmadesc_b[_dmadesc_last].qe.stqe_next = &_dmadesc_a[0]; 

        // Wait until we're now stuck in a _dmadesc_a loop;
        active_dma_buffer_output_count = 0;  
        while (!active_dma_buffer_output_count) {}      
  
        _dmadesc_b[_dmadesc_last].qe.stqe_next = &_dmadesc_b[0]; //append the old to the end of the old?
      }
        current_back_buffer_id ^= 1; 

}
```

After you wait to be in the other _dmadesc_ you append the old one to the old one. But this is at this point not the important thing. It is more important to have the new one connected right. I get what you were thinking: I first set the connection to the other dmadesc and then I have to reset it. But it appears, that it is not right to change it at this point. I guess it is to eary.
How ever If you switch the two lines  
_dmadesc_a[_dmadesc_last].qe.stqe_next = &_dmadesc_a[0];
 _dmadesc_b[_dmadesc_last].qe.stqe_next = &_dmadesc_b[0];
 everything works perfectly fine for me. To be more clear: you have to exchange the lines. Adding them would not fix the bug and adding them ~5 lines earlyier brings a different bug.
 By the way in the master brach there is currently quite a mess in these lines. For me it gets stuck there the first time it is called.
 Maybe you tried to fix it, but failed the merge?
 
 PS: Do you mind changing the min_refresh_rate in HUB75_I2S_CFG to an uint16_t? It is just one byte more and gives a lot of opportunities.
 
 PPS: I did something wrong with this Issue, it was previously a topic for a discussion but I think I fixed it now

**Comment by drvkmr** [comment]
Spent ages trying to fix this - thanks a lot @Lukaswnd !!!
