### ISSUE TITLE
Serpent-less arrangment

### ISSUE THREAD

**Issue by drvkmr** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#414]
Just saw the new updates with the non-standard chaining and am loving it. So much more clear and precise.
The only issue I realised instantly on updating is that it's not possible to chain panels in a serpent-less configuration. Am happy to work on implementing this change if you can help out @mrfaptastic, unless this is already possible and I am just missing it.

**Comment by mrfaptastic** [comment]
Thanks for the positive feedback! Glad that you love it!

Yeah I had burnt enough of my weekend on the update and took the assumption that nobody would use non-serpent chaining as it would require some long cables... But clearly I am wrong. 🤣

I'll take a look at it tonight as I think I can implement this quickly with another parameter to the constructor to serpentine.

**Comment by mrfaptastic** [comment]
Where are you going to put your ESP device on the back of the grid of panels (that is, where will the start point me)? Can it be the top right?

I can easily build support for a 'top right zigzag down' config. Couldn't be bothered doing the other three permutations.

**Comment by drvkmr** [comment]
It's bottom right in this setup, but if you do a partial implementation I can try and complete it.

**Comment by mrfaptastic** [comment]
Try with the esp32-dev branch of this library. Have added CHAIN_TOP_RIGHT_DOWN_ZZ

**Comment by mrfaptastic** [comment]
Sorted. Refer to Dev branch for the details

**Comment by drvkmr** [comment]
Cheers, I'll have a go this week.
