### ISSUE TITLE
ICN2037BP will it work?

### ISSUE THREAD

**Issue by iceblader2013** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#415]
Hey I got a P4 panel as you can see in the pictures but the labeling is different and I can't find the drivers in the list under running. Can you measure the pin assignment by where D and E is?

![IMG_20230315_124229](https://user-images.githubusercontent.com/53946847/225376417-4f95fa70-56d7-4a81-933b-65d10deb69ab.jpg)
![IMG_20230315_164818](https://user-images.githubusercontent.com/53946847/225376428-f9a83647-eb99-4f94-a037-430c5fae660d.jpg)
![IMG_20230315_164927](https://user-images.githubusercontent.com/53946847/225376432-a6f92c0c-c6fb-4305-b377-74025834b987.jpg)
![IMG_20230315_171106](https://user-images.githubusercontent.com/53946847/225376437-223c1f62-2f0c-4fa2-a2c7-5e0d8199f9ab.jpg)

**Comment by DarrylStrong** [comment]
The icn2037 are basic shift register drivers so should be fine.

Regarding d and e, test with a meter to see if the standard pins are connected to ground. I suspect that the legend is incorrect.

Cheers

Darryl

**Comment by iceblader2013** [comment]
what do you mean by standard pins on ground? ground on the plug or on the power connection?

**Comment by iceblader2013** [comment]
all pins are connected to ground

**Comment by DarrylStrong** [comment]
What re the other drive ics on the board?

There are the hc245, icn and what others?

**Comment by iceblader2013** [comment]
![IMG_20230315_211048](https://user-images.githubusercontent.com/53946847/225431153-4e4547d4-bd6b-45fd-bcf7-30275c37a3bf.jpg)

**Comment by iceblader2013** [comment]
the other all the same

**Comment by DarrylStrong** [comment]
There must be drivers for the rows, are there ics under the plastic moulding?

**Comment by iceblader2013** [comment]
hey under the plastic is 8 ics ICN2012

**Comment by DarrylStrong** [comment]
Good, those are 3 to 8 line demultiplexers.
[http://wiki.amperka.ru/_media/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D1%8B:rgb-led-matrix-64x32:icn2012_datasheet.pdf]url

Therefore for a 32:1 scan there must be 2 other row selects D and E.

This is the pinout most likely used.
[https://external-preview.redd.it/qA2JTWsbdDTG-HRStneUEd-kLK65XU8AfLjVzjyO82w.jpg?auto=webp&s=332c9721fceefa13a6073e2b744336236f33b621](url)

**Comment by board707** [comment]
> Have you a ideas ?

Swap the R G B pins?

**Comment by iceblader2013** [comment]
which are the rgb pins? ^^

**Comment by board707** [comment]
ESP32 pins, connected to R1 G1 B1 and R2 G2 B2 pins of HUB75 connector

**Comment by mrfaptastic** [comment]
Change the physical wiring or simply swap the GPIO/PIN/COLOR pin assignment in your code because your physical panel has been incorrectly made.
