### ISSUE TITLE
1 panel 128*64

### ISSUE THREAD

**Issue by Maestros95** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#417]
Hello my Friend

Congrats for your work.

i would like to ask you how can i connect 1 panel 128*64 with esp32. I have connected the panel with wires such here, but how can i connect the pin E? My panel has 1/32 scan with HUB75E and my chip is ICND2038S.

![CHIP](https://user-images.githubusercontent.com/100433872/225616965-04f27686-9d2b-4653-8a32-5fb04a15cc34.jpeg)

I would like to display jpeg, bitmap or png photo on the screen.

#define R1 25
#define G1 26
#define BL1 27
#define R2 14
#define G2 12
#define BL2 13
#define CH_A 23
#define CH_B 19
#define CH_C 5
#define CH_D 17
#define CH_E -1 // assign to any available pin if using two panels or 64x64 panels with 1/32 scan
#define CLK 16
#define LAT 4
#define OE 15

Are correct the defines?

#define PANEL_RES_X 128 // Number of pixels wide of each INDIVIDUAL panel module. 
#define PANEL_RES_Y 64 // Number of pixels tall of each INDIVIDUAL panel module.

#define NUM_ROWS 1 // Number of rows of chained INDIVIDUAL PANELS
#define NUM_COLS 1 // Number of INDIVIDUAL PANELS per ROW
#define PANEL_CHAIN NUM_ROWS*NUM_COLS    // total number of panels chained one to another

// Change this to your needs, for details on VirtualPanel pls see ChainedPanels example
#define SERPENT false
#define TOPDOWN false

Thanks!!!

![PICTURE](https://user-images.githubusercontent.com/100433872/225611762-c2b5f44e-aeec-419d-bc63-d40ace4c92d6.jpeg)

**Comment by board707** [comment]
> #define CH_E -1 

You should connect a real pin to E channel for your panel work

**Comment by Maestros95** [comment]
OK.

I connected on pin 33.

#define CH_E 33

But all define pins lines are comments.

**Comment by board707** [comment]
> But all define pins lines are comments

Why did you considered it as comments? By "#" mark?

**Comment by Maestros95** [comment]
![image](https://user-images.githubusercontent.com/100433872/225619463-8e993e4a-b33b-4b33-b973-72075a71ee7e.jpeg)

**Comment by board707** [comment]
Try 4_HueValueSpectrumDemo.ino example - it contains a full set of pins available for setup

**Comment by Maestros95** [comment]
Ok.
I set up the code about my panel.

Can i show pictures jpeg, bitmap or png photo on the screen on my panel?

**Comment by Maestros95** [comment]
In project ChainedPanelsAuroraDemo how can i set the pins? such as 4_HueValueSpectrumDemo.ino example.

**Comment by Maestros95** [comment]
> be

In ChainedPanelsAuroraDemo how can I set the pins?
