### ISSUE TITLE
AnimatedGIFPanel_SPIFFS

### ISSUE THREAD

**Issue by iceblader2013** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#422]
Hey when I try to verify the code from the example I get the error 'class fs::File' has no member named 'path'
does anyone have an idea?

**Comment by mrfaptastic** [comment]
What was the issue?

**Comment by mrfaptastic** [comment]
What was the issue?

**Comment by iceblader2013** [comment]
iam stupid. i hat the wrong esp32 Libery ^^ 
now i just have to combine it with mqtt then it would be perfect for my stream ^^

**Comment by mrfaptastic** [comment]
Nobody is here is stupid. They just haven't had the time to learn
