### ISSUE TITLE
Please help to display simple scrolling text on P10 LED matrix chained 32x16 LED matrix

### ISSUE THREAD

**Issue by abby3010** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#428]
**I'm trying to create a project using 3 matrix panels of 32x16 P10 LED panels chained together.**

I want to take 3 inputs from Bluetooth and display them on the LED panels.
Input 1: Single letter (In image - Letter "M")
Input 2: Single letter (In image - Letter "8")
Input 3: An extended text (In image - String "Brahmanada" - cropped to "Brahma" only)

I managed to display the first two inputs successfully as they are only single letters. However, I want the text to be scrolled if it does not fit in the given space. (If the string is small and fits in, then do not scroll)

I searched and tried out a lot but cannot make any code work for scrolling the text! I referred to @mrRobot62 's repository as well, but no luck! Then I figured out that his contribution is merged into this repo.

**It would be very helpful if someone can put even a simple example of scrolling text using this library on 32x16 chained panels for noobs like me!**

Sharing below the partial output of what I'm trying to achieve.

![image](https://user-images.githubusercontent.com/63793110/227172474-bccb2408-db09-4897-ae48-c0bca35213c6.png)

```
#include <ESP32-HUB75-MatrixPanel-I2S-DMA.h>

#define PANEL_RES_X 32      // Number of pixels wide of each INDIVIDUAL panel module. 
#define PANEL_RES_Y 16     // Number of pixels tall of each INDIVIDUAL panel module.
#define PANEL_CHAIN 3     // Total number of panels chained one to another
 
//MatrixPanel_I2S_DMA dma_display;
MatrixPanel_I2S_DMA *dma_display = nullptr;

uint16_t myBLACK = dma_display->color565(0, 0, 0);
uint16_t myWHITE = dma_display->color565(255, 255, 255);
uint16_t myRED = dma_display->color565(255, 0, 0);
uint16_t myGREEN = dma_display->color565(0, 255, 0);
uint16_t myBLUE = dma_display->color565(0, 0, 255);


// Input a value 0 to 255 to get a color value.
// The colours are a transition r - g - b - back to r.
// From: https://gist.github.com/davidegironi/3144efdc6d67e5df55438cc3cba613c8
uint16_t colorWheel(uint8_t pos) {
  if(pos < 85) {
    return dma_display->color565(pos * 3, 255 - pos * 3, 0);
  } else if(pos < 170) {
    pos -= 85;
    return dma_display->color565(255 - pos * 3, 0, pos * 3);
  } else {
    pos -= 170;
    return dma_display->color565(0, pos * 3, 255 - pos * 3);
  }
}

void drawText(int colorWheelOffset)
{
  dma_display->setTextSize(2);     // size 1 == 8 pixels high
  dma_display->setTextWrap(true); // Don't wrap at end of line - will do ourselves

  // dma_display->setCursor(5, 0);    // start at top left, with 8 pixel of spacing
  uint8_t w = 0;
  const char *str = "Brahmananda Technologies";
  for (w=0; w<strlen(str); w++) {
    dma_display->setTextColor(colorWheel((w*32)+colorWheelOffset));
    dma_display->print(str[w]);
  }
}


void setup() {

  // Module configuration
  HUB75_I2S_CFG mxconfig(
    PANEL_RES_X,   // module width
    PANEL_RES_Y,   // module height
    PANEL_CHAIN    // Chain length
  );

  //mxconfig.gpio.e = 18;
  //mxconfig.clkphase = false;
  //mxconfig.driver = HUB75_I2S_CFG::FM6126A;

  // Display Setup
  dma_display = new MatrixPanel_I2S_DMA(mxconfig);
  dma_display->begin();
  dma_display->setBrightness8(90); //0-255
  dma_display->clearScreen();

  drawText(0);
  
  // draw a box in the right side to display the two single characters
  dma_display->drawRect(79, 0, dma_display->width(), dma_display->height(), dma_display->color444(0, 0, 0));
  delay(3000);

  dma_display->setTextSize(2);   // 1 == 8 pixels ; 2 == 16 pixels
 
  // Set cursor and draw first character
  dma_display->setCursor(80, 0); 
  dma_display->print("8");
  // dma_display->print(" ");
  dma_display->print("M");

}

void loop() {
  
}
```

**Comment by mrfaptastic** [comment]
Why is setTextWrap = true

 Shouldn't it be false?

**Comment by abby3010** [comment]
I was just trying out things there!

**Comment by mrfaptastic** [comment]
I think your best bet would be to ask in the adafruit gfx library git account or ChatGPT. This library simply does the electrical pixel on the panel bit.

**Comment by board707** [comment]
32x16 1/8 panels does not require specific mapping

**Comment by abby3010** [comment]
> > Is it possible to put up a simple scroll text example

Even single color for the text is fine for me!

**Comment by mrRobot62** [comment]
Hi I remember, it was a little challenge to implement my solution for my 32x16 Display. That was the reason, that I re-implemented some graphical stuff again. As example the `write` and `scrolling text` behavior.

maybe it's possible for you, to go the same way as I Implement your own functions. 

You have to know, inside memory a font char is turned in 90deg cw.

**Comment by board707** [comment]
> You have to know, inside memory a font char is turned in 90deg cw.

In which library? AdafruitGFX fonts are not turned.

**Comment by board707** [comment]
> Even single color for the text is fine for me!

To scroll text, say, right  - print the message, wait 30mS, clear the screen and print the message one pixel right...and so on

**Comment by abby3010** [comment]
Hey everyone!
I was able to make it happen! 🙌

I'll definitely try to create a pull request on putting an example for scroll text using chained panels with VirtualMatrixPanel implementation.

Thank you for all of your support! 😊✨

**Comment by jfbvm** [comment]
> Hey everyone! I was able to make it happen! 🙌
> 
> I'll definitely try to create a pull request on putting an example for scroll text using chained panels with VirtualMatrixPanel implementation.
> 
> Thank you for all of your support! 😊✨

Hi abby3010,
Could you please post here the function of scrolling text, It would be a great help!!

**Comment by priya2212** [comment]
@abby3010 , It would be great if you share the changes here to make the scroll work. I am also stuck in scrolling text development.

**Comment by board707** [comment]
@priya2212 
What are the problems with scrolling? Can you display still text on your panels?

**Comment by priya2212** [comment]
@board707 , Sorry for delay in response. Yes, I am able to display the still text with some pixels shifting. 
I am using this piece of code but I see extreme flickering in the display - 
```
    FourScanPanel->flipDMABuffer();
    FourScanPanel->fillScreen(0);
    FourScanPanel->setCursor(w_text, y);
    FourScanPanel->setTextColor(FourScanPanel->color444(0, 0, 15));
    FourScanPanel->print(HELL);
    w_text--;
    if (w_text + len == 0)
    {
      w_text = 128;
    } 
```

**Comment by mrfaptastic** [comment]
Add a small delay between flipdmabuffer and clear screen.

**Comment by priya2212** [comment]
Added that, doesn't make any difference. Original Post is posted here - https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/issues/539

**Comment by mrfaptastic** [comment]
Create you own graphics buffer, draw to that, and once done, draw to this library by iterating through all rows and columns in the graphics buffer.

No need to use double buffering then.
