### ISSUE TITLE
Indexing error in x axis (SM5166PC Chipset)

### ISSUE THREAD

**Issue by Jiwno** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#434]
Hi, I have an issue while using the led matrix with the library.

I'm using a 96x48 pixel matrix with SM5166PC chipset and have index error in x axis.

As you can see in the image (0, 0) of the matrix doesn't start from left top corner.

I found that the index of x axis starts with 32-63 and then goes to 0-63.

32 to 63 index are repeated.

Is there any ways to set indexes of the matrix again or any other ways to solve this problem?
<img width="1052" alt="스크린샷 2023-04-08 오전 12 32 51" src="https://user-images.githubusercontent.com/57893252/230635897-08f60cb0-f061-47a0-8285-397f7796ec69.png">

**Comment by DarrylStrong** [comment]
Do you have a photo of the rear of the pcb?

**Comment by Jiwno** [comment]
> Do you have a photo of the rear of the pcb?

![IMG_2028](https://user-images.githubusercontent.com/57893252/230637224-8a17596a-16f1-4d83-8c2b-1686b5c772aa.JPG)
Here!!

But when I tested the example code '1_SimpleTestShapes', index seemed fine(after I defined pin e to 32 and I also defined pin e for the plasma example code as well)

Like this.
![IMG_2027](https://user-images.githubusercontent.com/57893252/230637432-9531d659-bf05-40eb-91c9-cf1454d93a6b.JPG)

**Comment by mrfaptastic** [comment]
So SM5166 compatibility works then? Looks good to me.

**Comment by Jiwno** [comment]
Yeah, index aligned well on shape test example code but not with the plasma code.

I don't know why but I think it works fine though

**Comment by mrfaptastic** [comment]
It could be a bug with the pattern plasma code to be honest.

**Comment by BaiTian6641** [comment]
I have the same issue with 96 x 48 panel and none of example code cannot display properly. However, there is a modify version of ESP32-HUB75-MatrixPanel-DMA library, that library seem work fine, but it only support ESP32.
https://www.waveshare.com/wiki/RGB-Matrix-P2.5-96x48-F#Demo_2

**Comment by mrfaptastic** [comment]
> https://www.waveshare.com/wiki/RGB-Matrix-P2.5-96x48-F#Demo_2

Good find. It would have been nice if they could have contributed to this library than make a custom copy.

**Comment by BaiTian6641** [comment]
![微信图片_20230617004346](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/16750326/e7878ffd-ff34-46a6-a11a-101cfe972fdd)

So, this is what panel display when I using none modified library. (Example is the BouncingSquares)

**Comment by BaiTian6641** [comment]
![f8b11884a5fdf1cc771535060417d31](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/16750326/9a1168a2-add9-479a-9ae3-75700d21c818)

For simple test shape example.

**Comment by BaiTian6641** [comment]
I make modify on waveshare's library, using current esp32_i2s_parallel_dma.hpp and esp32_i2s_parallel_dma.cpp. And result is this:
![97e25acc074f9c5405c852259e052db](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/16750326/8b2f6f98-d2c1-430e-9d5d-59207e292614)
This is SimpleTestShapes example.
![e6f40236a45877c3d2dfe0e1c927e1f](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/16750326/b0e3bc0d-8c4f-448b-b22b-394dd07d6eb3)
This is BouncingSquares example.

**Comment by BaiTian6641** [comment]
After set the invert_pclk to true in the gdma_lcd_parallel16.hpp, it works! @mrfaptastic @Jiwno 
![305d5cac36fac1e74d5bebee7923e98](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/16750326/0067419a-3876-4c51-9200-66fd1c79b5eb)
![e2490eb4a7144bd1c65bd6e9d921b36](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/16750326/02bba52d-86d2-4b83-b9f8-df5a7dda471c)
![e65707391fb5c1a8594024cf3815621](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/16750326/03dd96c2-11b4-4fbf-a341-443c6a1a2352)
![1f15217db7d7e5f7330eeecd2e884f2](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/16750326/c8e6e6f8-8ec2-4a8b-8618-e4bb203eb4b7)
So, here are some examples. The AuroraDemo example and BouncingSquares  example.

> Hi, I have an issue while using the led matrix with the library.
> 
> I'm using a 96x48 pixel matrix with SM5166PC chipset and have index error in x axis.
> 
> As you can see in the image (0, 0) of the matrix doesn't start from left top corner.
> 
> I found that the index of x axis starts with 32-63 and then goes to 0-63.
> 
> 32 to 63 index are repeated.
> 
> Is there any ways to set indexes of the matrix again or any other ways to solve this problem? <img alt="스크린샷 2023-04-08 오전 12 32 51" width="1052" src="https://user-images.githubusercontent.com/57893252/230635897-08f60cb0-f061-47a0-8285-397f7796ec69.png">

**Comment by mrfaptastic** [comment]
You found a bug that seemingly hasn't been detected for quite some time since I made changes to this library to include ESP32-S3 support.

You shouldn't need to edit the .hpp file to invert the clock (but you had to due toa bug).

You can pass to the `mxconfig.clkphase = true;` as part of the library config on initialisation.
