### ISSUE TITLE
Half of the matrix is red

### ISSUE THREAD

**Issue by DeltaW0x** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#449]
Hi, I've been trying to get this 32x64 FM6126A matrix to work with my original ESP32 for the past few days, but the lower half is red no matter what I do. I've tried the 1/8 scan mode, I've tried changing chip type, shortening the wires as much as possible, 
I even got a 3.3v -> 5v level shifter but the result is always the same. I tested the matrix on a RPI with the adafruit hub75 HAT and it does work perfectly with every example, so I'm really at a loss here. Maybe there's something wrong with my esp32? 
![PXL_20230508_225345002](https://user-images.githubusercontent.com/98419797/236955089-ef85f426-ab26-4b77-a4d1-9b000316a363.jpg)

**Comment by mrfaptastic** [comment]
> Maybe there's something wrong with my esp32?

Flip the R1, G1, B1 pins around (i.e. physically connect what should be R2, G2, B2) - If the problem then shows on the top half, then it's an issue with wiring.

Else, it could be a defective panel.

**Comment by DeltaW0x** [comment]
Flipped the color pins,  the problem does show up in the top half, so I checked the pinout again and it's still correct. I know for a fact that the matrix does work, so maybe there's something wrong with the esp32?

**Comment by mrfaptastic** [comment]
Change your red pin to another spare pin on your esp. Something wrong with the wiring or ESP.

**Comment by DeltaW0x** [comment]
The issues was indeed that my esp32 is faulty. I transfered all the secondary color pins to other spots on the board and  it got fixed. Thank you for helping! I'll replace the esp32 asap but at least I can work now.
![PXL_20230510_123454921](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/98419797/f8b30695-422c-46cd-8968-fefdb678879b)
