### ISSUE TITLE
Half screen no red or green, but white and blue OK

### ISSUE THREAD

**Issue by MrRady** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#451]
Hello,

I have a 128x64 panel, it's working fine but half of the panel missing green and red color.
The weird thing is white and blue colors are displayed correctly

The chips are ICN2037BP, with 74HC04D and 74HC245TS.

I have checked :
 - drivers, work with FM6126A
- brightness does nothing (40,128,255)
- With I2S speed at 8M, i have no more smalls artifacts but the half of screen still missing the two colors.

The weird thing is the white (R+G+B) seems to display correctly !
I am missing something or not ?

```
#define PANEL_RES_X 128      // Number of pixels wide of each INDIVIDUAL panel module. 
#define PANEL_RES_Y 64     // Number of pixels tall of each INDIVIDUAL panel module.
#define PANEL_CHAIN 1      // Total number of panels chained one to another
 
HUB75_I2S_CFG mxconfig(
    PANEL_RES_X,   // module width
    PANEL_RES_Y,   // module height
    PANEL_CHAIN    // Chain length
  );

  mxconfig.gpio.e = 32;
  mxconfig.gpio.oe = 33; //defaut 15 mais ca fait chier
  //mxconfig.clkphase = false;
  mxconfig.driver = HUB75_I2S_CFG::FM6126A;
  mxconfig.i2sspeed = HUB75_I2S_CFG::HZ_8M;
  // Display Setup
  dma_display = new MatrixPanel_I2S_DMA(mxconfig);
  
 
  dma_display->begin();
  //dma_display->setLatBlanking(4);
  dma_display->setBrightness8(128); //0-255
  dma_display->clearScreen();
  dma_display->fillScreen(myWHITE);
```
![PXL_20230509_083842408](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/9528667/a5fb566f-c58f-42a0-a686-2de6c8d7fead)
![PXL_20230510_135931812](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/9528667/3d136bdb-789f-4948-95e2-a12dce162679)
![PXL_20230510_140057554 NIGHT](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/9528667/9b914f2e-60e5-482e-aa21-43e6e02925cf)
![PXL_20230510_140535735](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/9528667/4ec1bbf6-39d0-4427-9196-8c4f801805a8)

**Comment by mrfaptastic** [comment]
Shorten your wiring? Seems like an electrical issue.
