### ISSUE TITLE
Allow `espressif/esp-idf-ci-action@v1` action

### ISSUE THREAD

**Issue by abrender** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#465]
Hi @mrfaptastic 

The `esp-idf` workflows aren't launching due to `espressif/esp-idf-ci-action@v1 is not allowed to be used in mrfaptastic/ESP32-HUB75-MatrixPanel-DMA. Actions in this workflow must be: within a repository owned by mrfaptastic, created by GitHub, or matching the following: actions/cache@v2, actions/checkout@v2, actions/setup-python@v2`. 

Example failed launch: https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/actions/runs/5050000918

Can you please allow this action to run by following these steps:
(1) Go to the Repo "Settings" page
(2) Click Actions -> General
(3) Select "Allow mrfaptastic, and select non-mrfaptastic, actions and reusable workflows"
(4) Add this entry for "Allow specified actions and reusable workflows": `espressif/esp-idf-ci-action@*`

Thanks!

**Comment by mrfaptastic** [comment]
Hi @abrender. Thank you kindly for this, I was wondering about this issue. I have implemented your change. Thanks!

![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/12006953/b87473e6-0f73-4fd2-b0a2-f7acc7933420)
