### ISSUE TITLE
3.0.8 -> 3.0.9 breaks ICN2037BP

### ISSUE THREAD

**Issue by sschueller** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#473]
This is more of an FYI for someone else having issues. If you see the following issue set your clkpase to false ```mxConfig.clkphase = false;``` 

true:

![P_20230702_154512](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/1180107/395b0bbf-4cea-479e-b109-42e6fe7ca0d5)

false:

![P_20230702_154419](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/1180107/2215132f-ae23-4199-9f86-8fc451a7ba15)

**Comment by mrfaptastic** [comment]
Yeah there was a bug in versions < 3.0.9 in that the clkphase value was always false and completely ignored.

**Comment by elan** [comment]
OMG, thank you so much, I was going crazy trying to figure out what broke.
