### ISSUE TITLE
selective brightness for different areas

### ISSUE THREAD

**Issue by jdeltoft** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#483]
Is there a way to change brightness for a specific area?  

I have 3 panels chained together, and would like to change each 64x64 panel brightness independently

**Comment by board707** [comment]
> Is there a way to change brightness for a specific area?

You can do it by changing the color brightness of the individual picture pixels.

**Comment by jdeltoft** [comment]
thanks!!! Yea, I thought I tried this but also I used say (225,0,0) vs (5,0,0) and now I'm using (2,0,0) for off.  This is non linear but just thought it wouldn't be that far from linear.  I also set the global brightness to max 255, not sure how much that plays into it but happy now.

![Uploading image.png…]()
