### ISSUE TITLE
how to use full range of 12 bit pixel color depth?

### ISSUE THREAD

**Issue by beta-tester** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#486]
hi,
how can i use the full range of 12 bit pixel color depth?

i am able to set the pixel color depth of the panel driver up to 12 bit,
but i only can draw text in colors at 565 (5-6 bits per color pixel).
the other function of the driver uses max. 8 bit per color pixel.

the background is i try to dimm my LED panel depending on the ambient light - ambient light range 0lx...10000lx. so the panel text will be readable at every ambient brightness without glaring or being illegible.

the setBrightness(uint8_t) function is not that precise as i need it will distort colors at the darker colors.

also trying to keep the panel brightness at maximum and dimming the color values in software does not the trick.
because the text functions still uses the 565 pixel color depth and makes not use of the full possible 12 bit per color pixel.
that results in color distortions and at lower values the text colpletely disapears sooner or later depending on its color values abter dimming.

what i have to do to draw text and other stuff in full 12 bit per color pixel?

my hardware:
- ESP32-dev board
- 2x 32x32 LED matrix panels in a chain

my software:
- Arduino-IDE; 1.8.19
- Arduino-ESP32: v2.0.11 (Esp Sdk: v4.4.5)
- ESP32 HUB75 LED MATRIX PANEL DMA Display: v3.0.9
- Adafruit GFX Library: v1.11.17
- Adafruit BusIO: v1.14.1

**Comment by mrfaptastic** [comment]
This hardware library simply uses AdafruitGFX for all drawing functions, which seems to limit text to 565 (16 bit unsigned).

I did try hacking AdafruitGFX with my GFX_Root library in another github repository of mine, I'm not sure if I change the text color functions however.
