### ISSUE TITLE
Missing Lines + overdraw 64x64 pannel

### ISSUE THREAD

**Issue by 0ekel** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#498]
Hi, I have a 64x64 Panel and get this weird overdraw/ missing lines 

is this explainable ?

![MicrosoftTeams-image (4)](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/64785361/ced1daee-2f83-403f-8d4d-fba2ea837f13)

![MicrosoftTeams-image (3)](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/64785361/23f9fd51-1c4a-4033-9665-e8c132cc4781)
![MicrosoftTeams-image (2)](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/64785361/9a514c75-98be-4009-998f-74987f41dbd4)

**Comment by mrfaptastic** [comment]
What scan rate is the panel? What chips? If you could provide photos of the chips so the markings can be identified that would help.

**Comment by 0ekel** [comment]
I have 2 panels I tried one of them has  icn2012 and fm 6124d chips and the other has RUC7258D and 6124d chips.
both panels have the same issue
they should both be 1/32 panels

do you need to change something in the code to make 1/32 panels work ? 

![MicrosoftTeams-image (7)](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/64785361/76a481b8-4afc-4a80-927d-b5f44d0a8db5)
![MicrosoftTeams-image (8)](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/64785361/ba0dc95b-73d9-4a2b-b733-4f9bc52d126c)
![MicrosoftTeams-image (5)](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/64785361/56c6c631-1eea-4788-95b8-ea05b80fbb93)
![MicrosoftTeams-image (6)](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/64785361/96a6da70-76d4-44ee-accd-ab429eb1bb8b)

**Comment by board707** [comment]
@0ekel 
Both your panels has absolutely standard drivers and should be supported very well by the library. Check your connections twice. Do you defined a E pin?

Are you sure that the panels has 32 scans?  Is there a identification string like "3535-p6-6464-s32-v4.0" on the rear side? Could you please show the photo of the rear side?

**Comment by 0ekel** [comment]
One of them is labled P3-64x64-2012-21A-1.0
and the other  P2.5-2020-32s-64x64-S2

if the panels should normally work it's probably because of my wiring that is wonky

**Comment by 0ekel** [comment]
I got it working, the pin I connected the D pin to on the Esp was faulty but not of, it stayed on so it looked like it was working when measuring but it had basically no signal to it

**Comment by board707** [comment]
> I got it working,

Great
