### ISSUE TITLE
High refresh rates (FPS > 200) possible with LED array?

### ISSUE THREAD

**Issue by roflmaostc** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#508]
Hi!

In my use case I want to let half of the LEDs flash for a very short moment in time.

If I try a flash time of ~2ms, by eye you can see that not all of LEDs were turned on.
With 10ms it looks good.

I was wondering, what is the shortest time I can show an image? What would I need to go, to let's say 1000Hz?

I've got the HUB75 with 32x32 and the ESP32-S3.

Any help is much appreciated!

Best,

Felix

**Comment by andresruizdev** [comment]
Hello @roflmaostc 

I think that you are refreshing the screen without use **double buffer**. I personally get 240 fps in some projects but without double buffer it is not greateful to watch the screen. 

Please check [this example](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/blob/master/examples/3_DoubleBuffer/3_DoubleBuffer.ino)
