### ISSUE TITLE
Is there a way to produce a desired refresh rate?

### ISSUE THREAD

**Issue by toine512** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#509]
Hi.

The lib produces an arbitrary refresh rate above `HUB75_I2S_CFG::min_refresh_rate`. Is there a way to manually tweak the computations in `MatrixPanel_I2S_DMA::allocateDMAmemory()` so that a defined refresh rate is produced?
I'm using the ESP32-S3, the LCD-CAM clock cannot be fine-tuned with the fractional divider when the source is the 160 MHz PLL.

**Comment by board707** [comment]
Did you tried to modify the code yourself?

**Comment by toine512** [comment]
> I'm using the ESP32-S3, the LCD-CAM clock cannot be fine-tuned with the fractional divider when the source is the 160 MHz PLL.

PLL_D2_CLK allows using full divider capability thus adjusting LCD-CAM frequency quite precisely. Then how can the refresh rate be computed from LCD_CAM frequency? Values printed in the log don't seem to match.
