### ISSUE TITLE
Build error on master

### ISSUE THREAD

**Issue by tsctrl** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#511]
1. In member function 'virtual VirtualCoords VirtualMatrixPanel::getCoords(int16_t, int16_t)':
error: suggest parentheses around arithmetic in operand of '^' [-Werror=parentheses]
if ((virt_y & 8) != ((virt_y & 16) >> 1)) { virt_y = (virt_y & 0b11000) ^ 0b11000 + (virt_y & 0b11100111); }

2. warning: variable 'num_dma_payload_colour_depths' set but not used [-Wunused-but-set-variable]
   int num_dma_payload_colour_depths = m_cfg.getPixelColorDepthBits();

**Comment by mrfaptastic** [comment]
Please raise a pull request if possible. Otherwise I'll take a look in the coming weeks.

Thank you kindly for identifying this.
