### ISSUE TITLE
Build error on espidf v5

### ISSUE THREAD

**Issue by dorianim** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#514]
Hello,

when trying to build the master branch with espidf, I get this error:
```
lib/ESP32-HUB75-MatrixPanel-DMA/src/platforms/esp32/esp32_i2s_parallel_dma.hpp:65:1: error: 'i2s_dev_t' does not name a type; did you mean 'i2s_dir_t'?
   65 | i2s_dev_t* getDev();
      | ^~~~~~~~~
      | i2s_dir_t
lib/ESP32-HUB75-MatrixPanel-DMA/src/platforms/esp32/esp32_i2s_parallel_dma.hpp:148:14: error: 'i2s_dev_t' does not name a type; did you mean 'i2s_dir_t'?
  148 |     volatile i2s_dev_t* _dev;
      |              ^~~~~~~~~
      |              i2s_dir_t
```

Adding
```cpp
#include <soc/i2s_struct.h>
```
to `esp32_i2s_parallel_dma.hpp` fixes it, but makes new errors come up:
![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/30153207/054feafb-37f7-4ae9-ab7e-345af4ee73d1)

Those errors can be fixed by adding
```cpp
#include <soc/i2s_periph.h>
```
to `esp32_i2s_parallel_dma.cpp` and changing the `%d` format specifiers to `%ld`.

**Comment by mrfaptastic** [comment]
Thank you for this contribution.
