### ISSUE TITLE
Panel 128x64 no driver

### ISSUE THREAD

**Issue by osadrac** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#517]
Hello, I have a Chinese panel without much information or driver datasheet, has anyone used something similar on an esp32? I used all the drivers in the library but without success.

I will send some images of the panel and components, if anyone has any ideas and can help I would be grateful

![20231024_230256](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/23412947/1e761c34-1be8-4bc7-9bc3-062701ffee8a)
![20231024_230345](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/23412947/de4c8f01-da06-4a15-a5aa-d395880ee66b)
![20231024_230548](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/23412947/37834a9e-5d3f-4936-ab31-f31233655d3c)
![20231027_180443](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/23412947/0908dc4f-2842-4b7b-82c5-8f022eaa9a32)
![20231027_180450](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/23412947/cbaf548d-d06a-4f2b-af2c-247e4a00224b)

with the SimpleTestShapes example it just looks like this
![Captura de tela 2023-10-27 181055](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/23412947/626aa7e3-f617-4f36-be50-ae0b20f375e1)

It also has a RUC7258 IC

**Comment by board707** [comment]
Chip SM16369 is a S-PWM type driver. These drivers have a fundamentally different control principles. It will not work with the library. Moreover, as far as I know, today none of the Arduino-compatible libraries for hub75 panels support S-PWM type drivers.
