### ISSUE TITLE
128x64-32S Not working

### ISSUE THREAD

**Issue by HennieLP** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#518]
![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/65833107/3aec731c-cd7b-4b26-af9a-0271dc6ea91f)
![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/65833107/df1c2eb0-34f1-4210-801d-81841c68e107)
![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/65833107/84f969eb-5334-48e7-aac1-a9757aad7985)
![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/65833107/3ba66d10-eb0f-4528-b02a-eced3e653e52)
Screen is just black if I press the reset button on the ESP screen some times Flashes

**Comment by HennieLP** [comment]
only flashing on reset if mxconfig.driver = HUB75_I2S_CFG::FM6126A is set

**Comment by board707** [comment]
Your panel's driver is DP3246. It require additional configuration before work and is not fully compatible with the library.
By the way, you panel should contains a three types of chip, but you show us only two.

**Comment by HennieLP** [comment]
thx
