### ISSUE TITLE
Support for 64x32 SM1666PF RUL6024 or a 64x32 RUC7258D RUL2038S?

### ISSUE THREAD

**Issue by michaelnaman** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#531]
Hi,

I'm struggling to get either of my panels to work, doubled checked wiring, power, etc and all good.

Is anyone able to confirm whether either of the driver combinations are supported and if they are, what is the config required to get them to run?

Thanks

**Comment by board707** [comment]
RUL6024 - unsupported driver.

 64x32 RUC7258D RUL2038S - should be fine if the panel has 16 scans

**Comment by michaelnaman** [comment]
![PXL_20231201_015341861](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/185379/e792c13c-9e3e-4438-a925-319ecbac89a9)
 I'veg ot this far with the 64x32 RUC7258D RUL2038S but the bottom half of the display is green. I rewired it twice now and tested different panels (same spec) plus there's a wire from the ground on the matrix power to the ESP32.

I'm using an ESP32 Wroom-32.

Any ideas on how to fix this?

**Comment by mrfaptastic** [comment]
@michaelnaman - what was the solution in the end?
