### ISSUE TITLE
X-axis off-by-one error after upgrade

### ISSUE THREAD

**Issue by derryx** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#537]
Hello!

I use your fantastic library for implementing a clock with a 64x32 pixel panel. That works great.

What the problem is now:
I upgraded the library to the latest master (last snapshot was roughtly a year old) and now the x-axis is off by one pixel to the left. When I draw a pixel at (0;0) it gets displayed at (63;0).

I just now can simply add 1 to the x values but that seems like a hack.

CU
Thomas

**Comment by derryx** [comment]
Seems to be the same issue as #516

**Comment by mrfaptastic** [comment]
mxconfig.clkphase value?

**Comment by derryx** [comment]
Seems to be the same issue as #516

**Comment by derryx** [comment]
That was it. Thanks!

**Comment by mjmokhtar** [comment]
can you tell me what its have 
I don't know how to fix it
