### ISSUE TITLE
1/10 scan

### ISSUE THREAD

**Issue by muthu920** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#553]
Is possible add custom scan to this library, our board is 1/10scan 80x40 led per panel, [ESP32-HUB75-MatrixPanel-DMA] works but 9th and 10th row is not printed for each scan because its printing 1/8s, is possible to convert to 1/10scan
![IMG-20231230-WA0004](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/13430806/92883495-02e6-46dd-b53f-1d42464371fa)

**Comment by board707** [comment]
Do you have several such panels? Try another one

**Comment by muthu920** [comment]
no i have only one panel, does this library support 1/10scan ?

**Comment by muthu920** [comment]
beacuse only 9th and 10th row missing but 8row display perfect

**Comment by muthu920** [comment]
driver ic RUC7258D

**Comment by mrfaptastic** [comment]
I think it's a defective panel. 

Can you try with another library like PxMatrix?

**Comment by muthu920** [comment]
ok i will check and update

> I think it's a defective panel.
> 
> Can you try with another library like PxMatrix?

Ok i will check and update

**Comment by muthu920** [comment]
![IMG-20231230-WA0008](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/13430806/e6f7e0e7-6386-4ce7-8f59-27a75eb9002c)

Using VirtualMatrix example

![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/13430806/4ea9277b-484f-4290-a28e-f2da5d9d2a57)

**Comment by muthu920** [comment]
if i use virtualDisp->fillScreen(virtualDisp->color565(100, 0, 0));

The all pixel show perfect 

![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/13430806/7b0af54b-9570-4248-91cc-ab7f14181def)

**Comment by muthu920** [comment]
when i set a pixel at   9th and 10th row but it show at 10th and 11th row 

![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/13430806/d93bdbb9-f940-4802-bbd5-5db4b11f0d8d)

![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/13430806/cb5ba0cd-5dcd-4086-bbd6-09cae2da1733)

**Comment by muthu920** [comment]
i think need to modify this library to 1/10Scan, any idea? Right now library scanning is 1/8

**Comment by muthu920** [comment]
> I think it's a defective panel.
> 
> Can you try with another library like PxMatrix?

does this library support 1/10scan

**Comment by board707** [comment]
What's the second chip aside 7258
 on your panel?

If you have a Stm32 bluepill or Rp2040 board, you can test the panel with DMD_Stm32 library.

**Comment by muthu920** [comment]
> What's the second chip aside 7258 on your panel?
> 
> If you have a Stm32 bluepill or Rp2040 board, you can test the panel with DMD_Stm32 library.

DP245D second chip

**Comment by muthu920** [comment]
I set to 

HUB75_I2S_CFG mxconfig(
        PANEL_RES_X * 2,              // DO NOT CHANGE THIS
        PANEL_RES_Y / 2,              // DO NOT CHANGE THIS
        PANEL_CHAIN           
    );

virtualDisp->setPhysicalPanelScanRate(FOUR_SCAN_32PX_HIGH);
and changed 

![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/13430806/1c2dabb0-a0b9-4363-9559-a51c5f005f40)

![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/13430806/1c2dabb0-a0b9-4363-9559-a51c5f005f40)


now i get 
![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/13430806/f6e90ee1-cea4-4d31-b789-7710de8b6f6c)

![image](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/13430806/8fcbf96c-e30d-470a-aa08-3bf317226de1)

**Comment by board707** [comment]
D245 is not a driver, should be yet another  one

**Comment by muthu920** [comment]
> DP245d is not a driver, should be yet another one

DP5125D

**Comment by board707** [comment]
Thank you. The good news that it is a standard driver, it should be supported by the library.

**Comment by muthu920** [comment]
> Thank you. The good news that it is a standard driver, it should be supported by the library.

I tried E pin gnd and Valid GPIO too, but same result


ok, i will buy one new board and check and update.

**Comment by muthu920** [comment]
> Thank you. The good news that it is a standard driver, it should be supported by the library.
> 
> It seems to me that the reason is a broken panel or bad connections. Check your board and panel for unsoldered pins.

In my board it mentioned P4-1921-80x40-10S-S2.0

**Comment by muthu920** [comment]
Tested with new panel but same result.

Panel not mistake, we test with other driver which comes with board it working perfect.

The problem with our library is it sacn 8 rows perfect but not scanning 9th and 10th row, does we need not modify virtiual to real pixel mapping for 1/10 scan because 1/8 scan working perfect but not 1/10 scan.

**Comment by mrfaptastic** [comment]
The library only natively supports 1/16 scan panels as outlined in the README, however, with some pixel-remapping  (I.e. Virtual Matrix class) we have been able to incorporate support for other random panels.

You'll need to change the virtual matrix class to add the necessary support for this panel.

**Comment by muthu920** [comment]
Ok thank you will update
