### ISSUE TITLE
I try test show video vertical with 3 chain led panel

### ISSUE THREAD

**Issue by phongans** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#568]
I have tried using and installing it as per the instructions, but there might have been a mistake somewhere.

![WhatsApp Image 2024-01-10 at 17 43 17_21e73048](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/124969647/59468e56-d9d4-479c-8243-1df57e6a93d8)

**Comment by board707** [comment]
looks like you specified a wrong panel dimensions

**Comment by phongans** [comment]
This is config dimensions

#include <ESP32-VirtualMatrixPanel-I2S-DMA.h>

// 2) Set pinout
#define PIN_E 32
#define PIN_A 22
#define PIN_B 21
#define PIN_C 2

// 3) Set configuration
#define PANEL_RES_X 64 // Number of pixels wide of each INDIVIDUAL panel module.
#define PANEL_RES_Y 64 // Number of pixels tall of each INDIVIDUAL panel module.

#define NUM_ROWS 4                     // Number of rows of chained INDIVIDUAL PANELS
#define NUM_COLS 1                     // Number of INDIVIDUAL PANELS per ROW
#define PANEL_CHAIN NUM_ROWS *NUM_COLS // total number of panels chained one to another

**Comment by board707** [comment]
Panels on the photo are definitely not a 64x64.

>  just connect with 2 panel

If you connect 2 panels, why did you set 4 panels in the code?

**Comment by phongans** [comment]
![WhatsApp Image 2024-01-10 at 17 53 16_99fd8272](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/124969647/a0614678-9803-438a-99c0-fec281434a4b)

This is show when set ROWS 2 & COLS 1

**Comment by board707** [comment]
You need a D pin for these panels

**Comment by phongans** [comment]
D pin? How to config D pin, when i set default with GPIO 17 

```
#define D_PIN 17
```

**Comment by board707** [comment]
I wrote because in your pin definitions above no D pin

**Comment by phongans** [comment]
> I wrote because in your pin definitions above there is no D pin

![IMG-20240110-WA0006.jpeg](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/124969647/90d0a764-70a5-4409-affe-4b57ceda1db1)

That okay, so how can show video @@

**Comment by board707** [comment]
looks correct
Any thanks for me? :)

Sorry, I have no experience with video output

**Comment by phongans** [comment]
Thanks so much @board707
