### ISSUE TITLE
Can't display GIF file, fill screen 

### ISSUE THREAD

**Issue by Nhatnt99** [mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#569]
I use Led panel 128x64 with Chip ICN2037BP. How to display any GIF frame size to fill screen connect 3xPanel 192x128? Please

![WhatsApp Image 2024-01-11 at 22 53 54_50de119d](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/150419778/4b6d9ef6-119a-4866-be2d-46433c0f141c)

I have video below: 

https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/assets/150419778/c5780a68-d6cd-4cc4-942a-45975452b270

**Comment by board707** [comment]
looks very similar to original. What's the problem?

**Comment by phongans** [comment]
I'm fixing okay
